/* ==========================================================================
   THE PAINTINGS

   This is the only file you need to touch to add a painting.

   To add one by hand:
     1. Put the image file in the  images/  folder.
     2. Copy one of the blocks below, paste it at the TOP of the list,
        and change the details.
     3. Save. Refresh the site.

   Or just say to Claude: "add the painting in images/whatever.jpg,
   it's called X, painted in 2026" and it will do all of this for you.

   FIELDS
     src      required - path to the image, always starting with "images/"
     width    required - the image's pixel width   (run tools/add-images.py
     height   required - the image's pixel height    to fill these in for you)
     title    the painting's name
     year     when it was painted - a year like "2025", or a full date like
              "2024-01-29". Shown exactly as you type it.
     medium   size and materials, e.g. '16" x 12"' or '16" x 12", cold-press'.
              NOTE the single quotes: inch marks are double quotes, so a value
              containing them must be wrapped in 'single quotes' instead.
     notes    an extra line for shows, prizes or provenance. Appears under the
              title when the painting is opened full-screen.
     alt      a plain description of what the painting shows, read aloud to
              visitors using a screen reader. Never shown on screen.

     watercolours  true = show it on the Watercolours page, which is the
                   front page of the site. Leave it out and the painting
                   stays in this file but is not shown anywhere.

   Titles, years and mediums are OPTIONAL - leave them as "" and nothing is
   shown rather than a blank line. The page shows the images on their own
   either way; the title appears over the painting on hover, and in full
   when a painting is opened full-screen.

   The order of this list is the order paintings appear. Newest at the top.
   ========================================================================== */

window.ARTWORKS = [
  {
    src: "images/lily-pads-no-2-brick-works.jpg",
    width: 2000,
    height: 1480,
    title: "Lily Pads No.2, Brick Works",
    year: "2026-06-23",
    medium: '12" x 16"',
    watercolours: true,
    alt: "Lily pads and a single white water lily with a yellow centre floating on deep blue-black water, seen from above.",
  },
  {
    src: "images/great-egret-brick-works.jpg",
    width: 2000,
    height: 1484,
    title: "Great Egret, Brick Works",
    year: "2026-07-09",
    medium: '12" x 16"',
    watercolours: true,
    alt: "A white egret standing at the edge of dark still water among fallen logs and cattails, tall green reeds crossing the foreground.",
  },
  {
    src: "images/tillys-moment-in-the-sun.jpg",
    width: 1475,
    height: 2000,
    title: "Tilly’s Moment in the Sun",
    year: "2026-08-03",
    medium: '16" x 12"',
    watercolours: true,
    alt: "A calico cat stretched out on her back in a patch of sunlight on a kitchen floor, a striped towel hanging from the dishwasher behind her.",
  },
  {
    src: "images/sailing-lake-muskoka.jpg",
    width: 2000,
    height: 1514,
    title: "Sailing Lake Muskoka",
    year: "2026-08-03",
    medium: '12" x 16"',
    watercolours: true,
    alt: "A small sailboat with a yellow and blue striped sail crossing sparkling open water, a dark pine-covered headland rising behind it.",
  },
  {
    src: "images/001-barrel-o-bobbin-apples.avif",
    width: 1043,
    height: 1400,
    title: "Barrel O'bobbin Apples",
    year: "2026-04-16",
    medium: '16" x 12"',
    watercolours: true,
    alt: "Apples in a bowl seen from above, resting on a deep blue cloth in strong shadow.",
  },
  {
    src: "images/002-glen-road-bridge-rider.avif",
    width: 1400,
    height: 1050,
    title: "Glen Road Bridge Rider",
    year: "2025-01-17",
    medium: '12" x 16"',
    watercolours: true,
    alt: "A cyclist with a red backpack riding along a pavement beneath a blaze of golden autumn trees.",
  },
  {
    src: "images/003-lake-superior-ne-shore.avif",
    width: 1400,
    height: 1054,
    title: "Lake Superior - NE Shore",
    year: "2026-02-11",
    medium: '12" x 16"',
    watercolours: true,
    alt: "Waves breaking white against a rocky shoreline, with evergreens and autumn colour on the headland behind.",
  },
  {
    src: "images/004-tilly-on-tap.avif",
    width: 1050,
    height: 1400,
    title: "Tilly on Tap",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
    alt: "A calico cat perched beside a kitchen sink, watching the water run from the tap.",
  },
  {
    src: "images/005-wood-duck.avif",
    width: 1400,
    height: 1014,
    title: "Wood Duck",
    year: "2025-12-08",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/006-at-the-water-s-edge.avif",
    width: 1011,
    height: 765,
    title: "At the Water's Edge",
    year: "2024-07-18",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/007-chinese-lanterns.avif",
    width: 1050,
    height: 1400,
    title: "Chinese Lanterns",
    year: "2024-01-26",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/008-black-crowned-night-heron.avif",
    width: 1400,
    height: 1052,
    title: "Black-crowned Night Heron",
    year: "2025-11-14",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/009-sandpipers-southampton.avif",
    width: 1400,
    height: 1022,
    title: "Sandpipers - Southampton",
    year: "2025-12-30",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/010-back-alley-harbord-village.avif",
    width: 1050,
    height: 1400,
    title: "Back Alley, Harbord Village",
    year: "2024-01-29",
    medium: '16" x 12"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Spring, 2024 - Juror: Ray McNeice",
    watercolours: true,
    alt: "A back alley in strong sun — a dark pickup truck parked in shadow, hydro poles and wires overhead, and a cyclist further down the lane.",
  },
  {
    src: "images/011-still-life-with-orange.avif",
    width: 1050,
    height: 1400,
    title: "Still Life with Orange",
    year: "2025-04-10",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/012-montauk-spray.avif",
    width: 1059,
    height: 1400,
    title: "Montauk Spray",
    year: "2026-01-13",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/013-interior-zen.avif",
    width: 1050,
    height: 1400,
    title: "Interior Zen",
    year: "2025-06-15",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/014-big-brother.avif",
    width: 467,
    height: 715,
    title: "Big Brother",
    year: "2024-10-06",
    medium: '22.5" x 15"',
    notes: "Exhibited at Artists' Choice Show - Papermill Gallery, Todmorden Mills - April, 2025",
    watercolours: true,
  },
  {
    src: "images/015-stepping-out.avif",
    width: 1055,
    height: 1400,
    title: "Stepping out",
    year: "2026-01-03",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/016-blue-watering-can-no-2.avif",
    width: 1052,
    height: 1400,
    title: "Blue Watering Can No. 2",
    year: "2026-01-07",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/017-something-s-brewing.avif",
    width: 948,
    height: 633,
    title: "Something's Brewing",
    year: "2022",
    medium: '15" x 22.5"',
    notes: "Gold Medal Award Toronto Watercolour Society Aquavision Group Show - Spring, 2022 Papermill Gallery at Todmorden Mills Juror: Merv Richardson, CSPWC, OSA",
    watercolours: true,
  },
  {
    src: "images/018-orange-shutter-shadows.avif",
    width: 1400,
    height: 1050,
    title: "Orange Shutter Shadows",
    year: "2025-04-20",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/019-canoe-at-rest.avif",
    width: 733,
    height: 496,
    title: "Canoe at Rest",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/020-dog-day-at-the-beaches.avif",
    width: 1400,
    height: 1050,
    title: "Dog Day at the Beaches",
    year: "2025-01-23",
    medium: '14" x 20"',
    notes: "Juried entry to Toronto Watercolour Aquavision Group Show - Spring 2025 Juror: Joanne Poluch",
    watercolours: true,
  },
  {
    src: "images/021-barney-on-tap.avif",
    width: 1400,
    height: 1050,
    title: "Barney on Tap",
    year: "2026-03-03",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/022-dragon-bowl-with-pears.avif",
    width: 1050,
    height: 1400,
    title: "Dragon Bowl with Pears",
    year: "2024-09-28",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/023-still-life-with-blue-and-white-bowl.avif",
    width: 939,
    height: 1400,
    title: "Still Life with Blue & White Bowl",
    year: "2025-10-07",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/024-red-winged-blackbird-branch-office.avif",
    width: 1052,
    height: 1400,
    title: "Red-winged Blackbird - Branch Office",
    year: "2025-08-09",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/025-lookout-point-above-don-valley-brick-works.avif",
    width: 1400,
    height: 1050,
    title: "Lookout Point (above Don Valley Brick Works)",
    year: "2023-08-10",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/026-sun-dappled-bike-trail.avif",
    width: 1400,
    height: 1050,
    title: "Sun dappled Bike Trail",
    year: "2024-12-24",
    medium: '12" x 16"',
    notes: "Juried entry to Toronto Watercolour Aquavision Group Show - Spring 2025 Juror: Joanne Poluch",
    watercolours: true,
  },
  {
    src: "images/027-ethereal-light.avif",
    width: 1400,
    height: 1050,
    title: "Ethereal Light",
    year: "2024-11-20",
    medium: '12" x 16"',
    notes: "Exhibited at Artists' Choice Show - Papermill Gallery, Todmorden Mills - April, 2025",
    watercolours: true,
  },
  {
    src: "images/028-woodbine-beach-in-winter.avif",
    width: 1400,
    height: 1050,
    title: "Woodbine Beach in Winter",
    year: "2024-07-02",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/029-trio-to-the-lookout-brick-works.avif",
    width: 1023,
    height: 775,
    title: "Trio to the Lookout, Brick Works",
    year: "2024-06-10",
    medium: '12" x 16"',
    notes: "Juried entry to Toronto Watercolour Aquavision Group Show - Fall, 2024 Juror: Brent Laycock CSPWC, OSA, RCA",
    watercolours: true,
  },
  {
    src: "images/030-off-balmy-beach-in-february.avif",
    width: 966,
    height: 653,
    title: "Off Balmy Beach in February",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/031-the-beaches-in-january.avif",
    width: 1400,
    height: 1050,
    title: "The Beaches in January",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/032-cat-scan.avif",
    width: 971,
    height: 642,
    title: "Cat Scan",
    year: "2022-04-23",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/033-killarney-rock-face.avif",
    width: 1400,
    height: 1050,
    title: "Killarney Rock Face",
    year: "2023-08-06",
    medium: '12" x 16"',
    notes: "Juried entry to Toronto Watercolour Society - Aquavision Group Show - Fall, 2023 - Juror: Carol Westcott, CSPW",
    watercolours: true,
  },
  {
    src: "images/034-faroe-islands-waterfall-no-1.avif",
    width: 1400,
    height: 1050,
    title: "Faroe Islands Waterfall No. 1",
    year: "2025-03-24",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/035-tree-twist.avif",
    width: 521,
    height: 667,
    title: "Tree Twist",
    year: "2024-07-28",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/036-the-ginkgo-on-ulster-street.avif",
    width: 1050,
    height: 1400,
    title: "The Ginkgo on Ulster Street",
    year: "2024",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/037-focalberry.avif",
    width: 1050,
    height: 1400,
    title: "Focalberry",
    year: "2024-07-10",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/038-november-ashbridges-bay.avif",
    width: 1050,
    height: 1400,
    title: "November - Ashbridges Bay",
    year: "2023-08-08",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/039-river-glow.avif",
    width: 577,
    height: 777,
    title: "River Glow",
    year: "2024-09-24",
    medium: '22.5" x 15"',
    notes: "Juried entry to Toronto Watercolour Aquavision Group Show - Fall, 2024 Juror: Brent Laycock CSPWC, OSA, RCA",
    watercolours: true,
  },
  {
    src: "images/040-light-and-shadow.avif",
    width: 1400,
    height: 843,
    title: "Light & Shadow",
    year: "",
    medium: '8" x 13"',
    watercolours: true,
  },
  {
    src: "images/041-pear-snatch.avif",
    width: 1050,
    height: 1400,
    title: "Pear Snatch",
    year: "2023-07-06",
    medium: '16" x 12"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Fall, 2023 - Juror: Carol Westcott, CSPW",
    watercolours: true,
  },
  {
    src: "images/042-winter-park-drive-reservation-lands.avif",
    width: 975,
    height: 694,
    title: "Winter - Park Drive Reservation Lands",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/043-southampton-beach.avif",
    width: 1050,
    height: 1400,
    title: "Southampton Beach",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/044-great-blue-heron-in-flight.avif",
    width: 1400,
    height: 1006,
    title: "Great Blue Heron in Flight",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/045-tropical-fish.avif",
    width: 1400,
    height: 1065,
    title: "Tropical Fish",
    year: "",
    medium: '8" x 12"',
    watercolours: true,
  },
  {
    src: "images/046-montauk-seascape-long-island.avif",
    width: 1400,
    height: 1026,
    title: "Montauk Seascape, Long Island",
    year: "2021",
    medium: '18" x 24"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Fall, 2021 - Juror: Joel Popadics, AWS, ASMA",
    watercolours: true,
  },
  {
    src: "images/047-into-the-woods.avif",
    width: 1400,
    height: 1050,
    title: "Into the Woods",
    year: "",
    medium: '22" x 16"',
    watercolours: true,
  },
  {
    src: "images/048-ruling-the-roost.avif",
    width: 584,
    height: 725,
    title: "Ruling the Roost",
    year: "2023-02-16",
    medium: '14" x 11"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Spring, 2023 - Juror: Ray McNeice",
    watercolours: true,
  },
  {
    src: "images/049-sunset-on-the-chobe-river-botswana.avif",
    width: 1400,
    height: 1040,
    title: "Sunset on the Chobe River, Botswana",
    year: "2025-07-10",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/050-orchard-street-lower-east-side.avif",
    width: 1050,
    height: 1400,
    title: "Orchard Street, Lower East Side",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/051-red-truck-lower-east-side-manhattan.avif",
    width: 426,
    height: 651,
    title: "Red Truck, Lower East Side, Manhattan",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/052-fountain-dip-central-park.avif",
    width: 1022,
    height: 1400,
    title: "Fountain Dip, Central Park",
    year: "2022",
    medium: '24" x 18"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Fall, 2022 - Juror: Logan Bales",
    watercolours: true,
  },
  {
    src: "images/053-a-moment-in-the-sun.avif",
    width: 1050,
    height: 1400,
    title: "A Moment in the Sun",
    year: "2023-07-06",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/054-milkweed.avif",
    width: 1400,
    height: 1050,
    title: "Milkweed",
    year: "2024-12-23",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/055-the-red-leaf.avif",
    width: 1400,
    height: 1050,
    title: "The Red Leaf",
    year: "2024-11-06",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/056-amsterdam.avif",
    width: 1400,
    height: 1057,
    title: "Amsterdam",
    year: "2025-12-08",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/057-barn-interior.avif",
    width: 1049,
    height: 1400,
    title: "Barn Interior",
    year: "2024-02-08",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/058-farm-near-churchill-innisfil-twp.avif",
    width: 1400,
    height: 1050,
    title: "Farm near Churchill, Innisfil Twp.",
    year: "2024-12-24",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/059-dragon-bowl-and-mandarins.avif",
    width: 1400,
    height: 1050,
    title: "Dragon Bowl and Mandarins",
    year: "2024-10-19",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/060-chestnut-study-no-2.avif",
    width: 1050,
    height: 1400,
    title: "Chestnut Study No. 2",
    year: "2024-09-05",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/061-gone-fishin.avif",
    width: 1400,
    height: 1050,
    title: "Gone Fishin'",
    year: "2024-08-04",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/062-the-red-backpack.avif",
    width: 1400,
    height: 1050,
    title: "The Red Backpack",
    year: "2023-08-13",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/063-sparrows-online.avif",
    width: 1400,
    height: 1050,
    title: "Sparrows Online",
    year: "2024-07-05",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/064-soaring.avif",
    width: 1400,
    height: 1050,
    title: "Soaring",
    year: "2024-11-07",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/065-lake-muskoka-october.avif",
    width: 1400,
    height: 1050,
    title: "Lake Muskoka, October",
    year: "2024-08-02",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/066-country-road-line-2.avif",
    width: 1400,
    height: 1052,
    title: "Country Road, Line 2",
    year: "2025-07",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/067-muskoka-rock-after-the-rain.avif",
    width: 1050,
    height: 1400,
    title: "Muskoka Rock after the Rain",
    year: "2024-07-30",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/068-sunlit-meadow-brick-works.avif",
    width: 1400,
    height: 1050,
    title: "Sunlit Meadow, Brick Works",
    year: "2024-05-28",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/069-water-lily-brick-works.avif",
    width: 1400,
    height: 1050,
    title: "Water Lily - Brick Works",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/070-cat-reflection.avif",
    width: 1400,
    height: 1046,
    title: "Cat Reflection",
    year: "2025-10-05",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/071-a-closer-look.avif",
    width: 1400,
    height: 1050,
    title: "A Closer Look",
    year: "2023-07",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/072-queen-solitaire.avif",
    width: 1050,
    height: 1400,
    title: "Queen Solitaire",
    year: "2024-05-30",
    medium: '16" x 12"',
    notes: "Juried entry to Toronto Watercolour Aquavision online Group Show - Fall 2025 Juror: Rayne Tunley",
    watercolours: true,
  },
  {
    src: "images/073-squatter.avif",
    width: 1050,
    height: 1400,
    title: "Squatter",
    year: "2024-04-07",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/074-shelf-life.avif",
    width: 1050,
    height: 1400,
    title: "Shelf Life",
    year: "",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/075-stair-to-stare.avif",
    width: 1400,
    height: 1050,
    title: "Stair to Stare",
    year: "2023-07-02",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/076-coffee-time.avif",
    width: 1400,
    height: 1050,
    title: "Coffee Time",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/077-what-goes-bump-in-the-night.avif",
    width: 1050,
    height: 1400,
    title: "What goes bump in the night?",
    year: "2024-01-08",
    medium: '22" x 15"',
    watercolours: true,
  },
  {
    src: "images/078-green-door-shadows.avif",
    width: 1050,
    height: 1400,
    title: "Green Door Shadows",
    year: "2025-04-17",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/079-dogwood-after-the-rain-no-2.avif",
    width: 1050,
    height: 1400,
    title: "Dogwood after the Rain No. 2",
    year: "",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/080-backlit-plant.avif",
    width: 468,
    height: 708,
    title: "Backlit Plant",
    year: "2023-01-31",
    medium: '14.5" x 9.75"',
    watercolours: true,
  },
  {
    src: "images/081-chestnut-study-no-1.avif",
    width: 955,
    height: 675,
    title: "Chestnut Study No. 1",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/082-great-blue-heron-de-grassi-point.avif",
    width: 1400,
    height: 937,
    title: "Great Blue Heron, De Grassi Point",
    year: "",
    medium: '6" x 10"',
    watercolours: true,
  },
  {
    src: "images/083-mallard-no-3.avif",
    width: 1400,
    height: 1050,
    title: "Mallard No. 3",
    year: "2023-08-02",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/084-catching-the-light.avif",
    width: 1050,
    height: 1400,
    title: "Catching the Light",
    year: "2024-07-21",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/085-cast-shadows.avif",
    width: 1050,
    height: 1400,
    title: "Cast Shadows",
    year: "2024-08-07",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/086-meadow-in-winter-no-1-de-grassi-point.avif",
    width: 1400,
    height: 1050,
    title: "Meadow in Winter No. 1, De Grassi Point",
    year: "",
    medium: '22.5" x 30"',
    watercolours: true,
  },
  {
    src: "images/087-brooding-sky-lake-simcoe.avif",
    width: 973,
    height: 654,
    title: "Brooding Sky, Lake Simcoe",
    year: "",
    medium: '8.25" x 12"',
    watercolours: true,
  },
  {
    src: "images/088-sailboat-at-anchor-de-grassi-point.avif",
    width: 1400,
    height: 1050,
    title: "Sailboat at Anchor, De Grassi Point",
    year: "",
    medium: '15" x 22"',
    watercolours: true,
  },
  {
    src: "images/089-forest-glade-de-grassi-point.avif",
    width: 1400,
    height: 1050,
    title: "Forest Glade, De Grassi Point",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/090-lake-muskoka-contre-jour.avif",
    width: 926,
    height: 648,
    title: "Lake Muskoka - Contre Jour",
    year: "",
    medium: '15" x 22"',
    watercolours: true,
  },
  {
    src: "images/091-red-rock-at-montauk.avif",
    width: 1003,
    height: 1400,
    title: "Red Rock at Montauk",
    year: "2021",
    medium: '24" x 18"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Fall, 2021 - Juror: Joel Popadics, AWS, ASMA",
    watercolours: true,
  },
  {
    src: "images/092-night-traffic-mt-pleasant.avif",
    width: 1400,
    height: 1050,
    title: "Night Traffic, Mt. Pleasant",
    year: "2025-01-20",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/093-the-burrow-brick-works.avif",
    width: 945,
    height: 682,
    title: "The Burrow, Brick Works",
    year: "",
    medium: '10" x 14"',
    watercolours: true,
  },
  {
    src: "images/094-goldfish-no-1.avif",
    width: 1400,
    height: 1050,
    title: "Goldfish No. 1",
    year: "2024-07-12",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/095-robert-street-at-college.avif",
    width: 1051,
    height: 1400,
    title: "Robert Street at College",
    year: "2025-11-26",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/096-goldfish-no-2.avif",
    width: 1400,
    height: 1050,
    title: "Goldfish No. 2",
    year: "2025-05-27",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/097-mud-creek-looking-west.avif",
    width: 1041,
    height: 1400,
    title: "Mud Creek - looking west",
    year: "2026-01-15",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/098-canoe-bound.avif",
    width: 1400,
    height: 1050,
    title: "Canoe Bound",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/099-red-beetle-on-life-support.avif",
    width: 1400,
    height: 1043,
    title: "Red Beetle on Life Support",
    year: "2025-08-06",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/100-red-winged-blackbird.avif",
    width: 1050,
    height: 1400,
    title: "Red-winged blackbird",
    year: "2023-07",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/101-october-reflections-brick-works.avif",
    width: 475,
    height: 759,
    title: "October Reflections, Brick Works",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/102-pink-house-bermuda.avif",
    width: 1400,
    height: 1066,
    title: "Pink House, Bermuda",
    year: "",
    medium: '16" x 20"',
    watercolours: true,
  },
  {
    src: "images/103-cap-taillot-near-st-tropez.avif",
    width: 992,
    height: 656,
    title: "Cap Taillot, near St. Tropez",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/104-cabot-trail.avif",
    width: 1400,
    height: 1050,
    title: "Cabot Trail",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/105-park-drive-reservation-lands-summer.avif",
    width: 1400,
    height: 1044,
    title: "Park Drive Reservation Lands, Summer",
    year: "2025-08-10",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/106-evening-glow-lake-kipawa-quebec.avif",
    width: 1020,
    height: 728,
    title: "Evening Glow - Lake Kipawa, Quebec",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/107-lake-kipawa-quebec.avif",
    width: 747,
    height: 489,
    title: "Lake Kipawa, Quebec",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/108-the-pink-bike.avif",
    width: 1400,
    height: 1055,
    title: "The Pink Bike",
    year: "2025",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/109-my-goatee.avif",
    width: 1050,
    height: 1400,
    title: "My Goatee",
    year: "2024-03-28",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/110-feeling-a-little-sheepish-at-riverdale-farm.avif",
    width: 973,
    height: 687,
    title: "Feeling a little sheepish at Riverdale Farm",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/111-sheep-ahoy-riverdale-farm.avif",
    width: 945,
    height: 668,
    title: "Sheep Ahoy, Riverdale Farm",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/112-rabble-rousers.avif",
    width: 1400,
    height: 1034,
    title: "Rabble Rousers",
    year: "2023-07-14",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/113-dee-dee-samoyed-of-destiny.avif",
    width: 515,
    height: 712,
    title: "Dee Dee, Samoyed of Destiny",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/114-battle-stations.avif",
    width: 1050,
    height: 1400,
    title: "Battle Stations!",
    year: "2025-05-27",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/115-barney-against-the-grain.avif",
    width: 1400,
    height: 1050,
    title: "Barney against the Grain",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/116-on-break-lower-east-side-nyc.avif",
    width: 1050,
    height: 1400,
    title: "On break - Lower East Side, NYC",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/117-red-sox-win-the-series-oct-2018.avif",
    width: 425,
    height: 654,
    title: "Red Sox win the Series! Oct. 2018",
    year: "2018",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/118-at-the-beaches-in-january.avif",
    width: 1400,
    height: 1050,
    title: "At the Beaches in January",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/119-vigil-at-the-beaches.avif",
    width: 705,
    height: 249,
    title: "Vigil at the Beaches",
    year: "",
    medium: '8" x 23"',
    watercolours: true,
  },
  {
    src: "images/120-frozen-river.avif",
    width: 857,
    height: 246,
    title: "Frozen River",
    year: "",
    medium: '9" x 28"',
    watercolours: true,
  },
  {
    src: "images/121-agawa-rock-lake-superior-provincial-park.avif",
    width: 1400,
    height: 1050,
    title: "Agawa Rock, Lake Superior Provincial Park",
    year: "",
    medium: '16" x 20"',
    watercolours: true,
  },
  {
    src: "images/122-wit-s-end-lake-simcoe.avif",
    width: 1400,
    height: 1050,
    title: "Wit's End, Lake Simcoe",
    year: "",
    medium: '22.5" x 30"',
    watercolours: true,
  },
  {
    src: "images/123-lily-pads-lake-simcoe.avif",
    width: 1400,
    height: 1050,
    title: "Lily Pads, Lake Simcoe",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/124-lily-pads-brick-works.avif",
    width: 1400,
    height: 1041,
    title: "Lily Pads, Brick Works",
    year: "2024-09-01",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/125-oak-leaves-de-grassi-point.avif",
    width: 1399,
    height: 1022,
    title: "Oak Leaves, De Grassi Point",
    year: "",
    medium: '8" x 12"',
    watercolours: true,
  },
  {
    src: "images/126-sunlit-stroll.avif",
    width: 1400,
    height: 1035,
    title: "Sunlit Stroll",
    year: "2025-07",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/127-old-barn-innisfree.avif",
    width: 996,
    height: 613,
    title: "Old Barn, Innisfree",
    year: "",
    medium: '10" x 16"',
    watercolours: true,
  },
  {
    src: "images/128-woodbine-beach-in-winter-no-2.avif",
    width: 941,
    height: 676,
    title: "Woodbine Beach in Winter No.2",
    year: "2023-04-23",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/129-killarney-east-lighthouse.avif",
    width: 949,
    height: 682,
    title: "Killarney East Lighthouse",
    year: "",
    medium: '10.25" x 14"',
    watercolours: true,
  },
  {
    src: "images/130-halfway-log-dump-bruce-peninsula.avif",
    width: 1400,
    height: 1050,
    title: "Halfway Log Dump, Bruce Peninsula",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/131-wetland-hardy-lake-provincial-park.avif",
    width: 955,
    height: 743,
    title: "Wetland, Hardy Lake Provincial Park",
    year: "",
    medium: '22" x 30"',
    watercolours: true,
  },
  {
    src: "images/132-pink-rock-killarney.avif",
    width: 749,
    height: 495,
    title: "Pink Rock, Killarney",
    year: "2021-12-24",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/133-killarney.avif",
    width: 1400,
    height: 1049,
    title: "Killarney",
    year: "",
    medium: '7" x 9"',
    watercolours: true,
  },
  {
    src: "images/134-firing-squad-fort-york-guard-musket-drill.avif",
    width: 1400,
    height: 1050,
    title: "Firing Squad - Fort York Guard: Musket Drill",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/135-drum-major-canadian-regiment-of-fencible-infantry-fo.avif",
    width: 497,
    height: 751,
    title: "Drum Major, Canadian Regiment of Fencible Infantry (Fort York Guard)",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/136-get-to-the-point-fort-york-guard.avif",
    width: 1400,
    height: 1050,
    title: "Get to the Point - Fort York Guard",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/137-flowerpot-island-no-1-bruce-peninsula.avif",
    width: 1052,
    height: 1400,
    title: "Flowerpot Island No. 1, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/138-flower-pot-island-no-2-bruce-peninsula.avif",
    width: 1050,
    height: 1400,
    title: "Flower Pot Island No. 2 Bruce Peninsula",
    year: "",
    medium: '22" x 15"',
    watercolours: true,
  },
  {
    src: "images/139-flowerpot-island-from-the-water.avif",
    width: 1400,
    height: 1050,
    title: "Flowerpot Island from the water",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/140-indian-head-cove-bruce-peninsula.avif",
    width: 1019,
    height: 1400,
    title: "Indian Head Cove, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/141-fathom-five-national-marine-park.avif",
    width: 917,
    height: 290,
    title: "Fathom Five National Marine Park",
    year: "2019-01-02",
    medium: '7.5" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/142-muskoka-cottage-three-mile-lake.avif",
    width: 1022,
    height: 681,
    title: "Muskoka Cottage - Three Mile Lake",
    year: "2020-09-08",
    medium: '15" x 22"',
    watercolours: true,
  },
  {
    src: "images/143-sauble-falls.avif",
    width: 1400,
    height: 1040,
    title: "Sauble Falls",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/144-abandoned-farmhouse-line-3-innisfil-twp.avif",
    width: 1400,
    height: 1006,
    title: "Abandoned Farmhouse - Line 3, Innisfil Twp.",
    year: "",
    medium: '10" x 14"',
    watercolours: true,
  },
  {
    src: "images/145-innisfree-barn-2nd-line-innisfil-twp.avif",
    width: 1022,
    height: 558,
    title: "Innisfree Barn, 2nd Line, Innisfil Twp.",
    year: "",
    medium: '13" x 24"',
    watercolours: true,
  },
  {
    src: "images/146-red-canoe-lake-simcoe.avif",
    width: 478,
    height: 735,
    title: "Red Canoe, Lake Simcoe",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/147-lake-simcoe-clouds-no-1.avif",
    width: 1400,
    height: 1050,
    title: "Lake Simcoe Clouds No. 1",
    year: "2024-07-21",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/148-storm-cloud-no-1-lake-simcoe.avif",
    width: 731,
    height: 476,
    title: "Storm Cloud No. 1, Lake Simcoe",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/149-storm-cloud-no-2-lake-simcoe.avif",
    width: 1050,
    height: 1400,
    title: "Storm Cloud No. 2, Lake Simcoe",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/150-swallowtail-with-joe-pye-weed.avif",
    width: 470,
    height: 728,
    title: "Swallowtail with Joe Pye Weed",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/151-laser-focus-lake-simcoe.avif",
    width: 972,
    height: 627,
    title: "Laser Focus, Lake Simcoe",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/152-goldenrod-lake-simcoe.avif",
    width: 486,
    height: 727,
    title: "Goldenrod, Lake Simcoe",
    year: "2020-05-26",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/153-lily-pad-de-grassi-point-lake-simcoe.avif",
    width: 494,
    height: 748,
    title: "Lily Pad, De Grassi Point, Lake Simcoe",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/154-august-de-grassi-point.avif",
    width: 1050,
    height: 1400,
    title: "August, De Grassi Point",
    year: "",
    medium: '14" x 11"',
    watercolours: true,
  },
  {
    src: "images/155-summer-through-the-bough-de-grassi-point.avif",
    width: 1050,
    height: 1400,
    title: "Summer through the Bough, De Grassi Point",
    year: "",
    medium: '14" x 11"',
    watercolours: true,
  },
  {
    src: "images/156-under-the-willow-de-grassi-point.avif",
    width: 1050,
    height: 1400,
    title: "Under the Willow, De Grassi Point",
    year: "",
    medium: '14" x 11"',
    watercolours: true,
  },
  {
    src: "images/157-purple-haze-de-grassi-point.avif",
    width: 1050,
    height: 1400,
    title: "Purple Haze, De Grassi Point",
    year: "",
    medium: '14" x 11"',
    watercolours: true,
  },
  {
    src: "images/158-kayak-days-lake-simcoe.avif",
    width: 1050,
    height: 1400,
    title: "Kayak Days, Lake Simcoe",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/159-towering-pine-de-grassi-point.avif",
    width: 463,
    height: 701,
    title: "Towering Pine, De Grassi Point",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/160-swallowtail-de-grassi-point.avif",
    width: 1399,
    height: 1397,
    title: "Swallowtail, De Grassi Point",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/161-provincetown-cape-cod.avif",
    width: 1400,
    height: 1053,
    title: "Provincetown, Cape Cod",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/162-caledon-hills.avif",
    width: 1050,
    height: 1400,
    title: "Caledon Hills",
    year: "2020",
    medium: '22" x 15"',
    watercolours: true,
  },
  {
    src: "images/163-ithaca-falls-at-sunset.avif",
    width: 1050,
    height: 1400,
    title: "Ithaca Falls at Sunset",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/164-september-evergreen-brick-works.avif",
    width: 1400,
    height: 1050,
    title: "September, Evergreen Brick Works",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/165-don-valley-brick-works.avif",
    width: 1036,
    height: 1400,
    title: "Don Valley Brick Works",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/166-fall-sumac-at-the-brick-works.avif",
    width: 1050,
    height: 1400,
    title: "Fall Sumac at the Brick Works",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/167-park-drive-reservation-lands.avif",
    width: 1400,
    height: 1050,
    title: "Park Drive Reservation Lands",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/168-rosedale-to-summerhill.avif",
    width: 1050,
    height: 1400,
    title: "Rosedale to Summerhill",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/169-the-night-bus.avif",
    width: 1050,
    height: 1400,
    title: "The Night Bus",
    year: "",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/170-in-transit.avif",
    width: 1050,
    height: 1400,
    title: "In Transit",
    year: "2024-01-20",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/171-night-bus-82.avif",
    width: 1400,
    height: 1050,
    title: "Night Bus 82",
    year: "2024-12-08",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/172-at-the-crossroads.avif",
    width: 970,
    height: 539,
    title: "At the Crossroads",
    year: "2024-03-01",
    medium: "",
    watercolours: true,
  },
  {
    src: "images/173-safe-crossing.avif",
    width: 993,
    height: 661,
    title: "Safe Crossing",
    year: "2024-10-06",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/174-rainbow-glen-road-bridge.avif",
    width: 930,
    height: 1400,
    title: "Rainbow, Glen Road Bridge",
    year: "",
    medium: '22" x 15"',
    watercolours: true,
  },
  {
    src: "images/175-peace-in-the-hood.avif",
    width: 1047,
    height: 1400,
    title: "Peace in the Hood",
    year: "2023-07-16",
    medium: '16" x 12"',
    watercolours: true,
  },
  {
    src: "images/176-kittenaid.avif",
    width: 1050,
    height: 1400,
    title: "KittenAid",
    year: "2022",
    medium: '24" x 18"',
    notes: "Juried entry to group exhibition \"Life Doesn't Stand Still\" at Leslie Grove Gallery - Nov 16 - Dec 4, 2022",
    watercolours: true,
  },
  {
    src: "images/177-barney-s-got-that-sinking-feeling-again.avif",
    width: 1050,
    height: 1400,
    title: "Barney's got that sinking feeling again",
    year: "",
    medium: '22.5" x 15"',
    watercolours: true,
  },
  {
    src: "images/178-tilly-rack-em-up.avif",
    width: 686,
    height: 446,
    title: "Tilly rack 'em up",
    year: "",
    medium: '10" x 14"',
    watercolours: true,
  },
  {
    src: "images/179-barney-takes-a-sip.avif",
    width: 1400,
    height: 1050,
    title: "Barney takes a sip",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/180-cat-nap.avif",
    width: 632,
    height: 709,
    title: "Cat Nap",
    year: "",
    medium: '11" x 10"',
    watercolours: true,
  },
  {
    src: "images/181-spin-dry.avif",
    width: 519,
    height: 720,
    title: "Spin Dry",
    year: "",
    medium: '14" x 10.25"',
    watercolours: true,
  },
  {
    src: "images/182-tilly-undercover.avif",
    width: 932,
    height: 1400,
    title: "Tilly Undercover",
    year: "2023",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/183-a-walk-in-the-snow.avif",
    width: 530,
    height: 744,
    title: "A Walk in the Snow",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/184-cahoon-hollow-beach-cape-cod.avif",
    width: 1050,
    height: 1400,
    title: "Cahoon Hollow Beach, Cape Cod",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/185-lighthouse-tobermory.avif",
    width: 1050,
    height: 1400,
    title: "Lighthouse, Tobermory",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/186-flowerpot-island-far-side-bruce-peninsula.avif",
    width: 1050,
    height: 1400,
    title: "Flowerpot Island - Far Side, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/187-halfway-log-dump-beach-bruce-peninsula.avif",
    width: 1047,
    height: 1400,
    title: "Halfway Log Dump Beach, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/188-between-a-rock-and-a-hard-place-halfway-log-dump-bea.avif",
    width: 1400,
    height: 1050,
    title: "Between a Rock and a Hard Place - Halfway Log Dump Beach, Tobermory",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/189-cranberry-bog-frog-killarney.avif",
    width: 694,
    height: 500,
    title: "Cranberry Bog Frog, Killarney",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/190-emmett-lake-bruce-peninsula.avif",
    width: 1050,
    height: 1400,
    title: "Emmett Lake, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/191-georgian-bay-island.avif",
    width: 1400,
    height: 1050,
    title: "Georgian Bay island",
    year: "2023-08-19",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/192-forest-glade-emmett-lake-bruce-peninsula.avif",
    width: 1050,
    height: 1400,
    title: "Forest Glade, Emmett Lake, Bruce Peninsula",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/193-killarney-paddle.avif",
    width: 696,
    height: 497,
    title: "Killarney Paddle",
    year: "",
    medium: '10" x 14"',
    watercolours: true,
  },
  {
    src: "images/194-killarney-reflections.avif",
    width: 1022,
    height: 668,
    title: "Killarney Reflections",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/195-the-fallen-at-hardy-lake-provincial-park.avif",
    width: 1400,
    height: 1050,
    title: "The Fallen at Hardy Lake Provincial Park",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/196-thistle-don-valley.avif",
    width: 466,
    height: 743,
    title: "Thistle, Don Valley",
    year: "2022",
    medium: '22.5" x 15"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Fall, 2022 - Juror: Logan Bales",
    watercolours: true,
  },
  {
    src: "images/197-gold-fish-and-lily-pad.avif",
    width: 1395,
    height: 1400,
    title: "Gold Fish and Lily Pad",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/198-lily-pads-no-1-lake-simcoe.avif",
    width: 1400,
    height: 1400,
    title: "Lily Pads, No. 1 Lake Simcoe",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/199-lily-pads-no-2-lake-simcoe.avif",
    width: 695,
    height: 700,
    title: "Lily Pads No. 2, Lake Simcoe",
    year: "",
    medium: '10" x 10"',
    watercolours: true,
  },
  {
    src: "images/200-lily-pads-muskoka.avif",
    width: 1391,
    height: 1400,
    title: "Lily Pads, Muskoka",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/201-lily-pads-with-dragonflies.avif",
    width: 1400,
    height: 1396,
    title: "Lily Pads with Dragonflies",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/202-raspberry-flowers.avif",
    width: 1390,
    height: 1400,
    title: "Raspberry Flowers",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/203-wild-rose.avif",
    width: 1370,
    height: 1399,
    title: "Wild Rose",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/204-thistle.avif",
    width: 1370,
    height: 1399,
    title: "Thistle",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/205-raspberry.avif",
    width: 1353,
    height: 1400,
    title: "Raspberry",
    year: "",
    medium: '12" x 12"',
    watercolours: true,
  },
  {
    src: "images/206-dogwood-after-the-rain.avif",
    width: 971,
    height: 1400,
    title: "Dogwood after the Rain",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/207-wasp-at-work.avif",
    width: 503,
    height: 739,
    title: "Wasp at Work",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/208-lemon-tree.avif",
    width: 1400,
    height: 1065,
    title: "Lemon Tree",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/209-carps-pond-fontainebleau.avif",
    width: 897,
    height: 581,
    title: "Carps Pond, Fontainebleau",
    year: "",
    medium: '10" x 14"',
    watercolours: true,
  },
  {
    src: "images/210-falling-falling-fallen-ragged-falls.avif",
    width: 929,
    height: 1400,
    title: "Falling, Falling, Fallen, Ragged Falls",
    year: "",
    medium: '18" x 12"',
    watercolours: true,
  },
  {
    src: "images/211-ice-glaze-ragged-falls.avif",
    width: 919,
    height: 1400,
    title: "Ice Glaze, Ragged Falls",
    year: "",
    medium: '18" x 12"',
    watercolours: true,
  },
  {
    src: "images/212-upstream-ragged-falls.avif",
    width: 972,
    height: 1400,
    title: "Upstream, Ragged Falls",
    year: "",
    medium: '18" x 12"',
    watercolours: true,
  },
  {
    src: "images/213-lone-pine.avif",
    width: 1032,
    height: 1400,
    title: "Lone Pine",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/214-snow-cone.avif",
    width: 1400,
    height: 1050,
    title: "Snow Cone",
    year: "",
    medium: '16" x 22"',
    watercolours: true,
  },
  {
    src: "images/215-echo-lake-fayette-maine.avif",
    width: 1050,
    height: 1400,
    title: "Echo Lake, Fayette, Maine",
    year: "",
    medium: '22" x 16"',
    watercolours: true,
  },
  {
    src: "images/216-blue-watering-can.avif",
    width: 1014,
    height: 1400,
    title: "Blue Watering Can",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/217-mallard-no-1-brick-works.avif",
    width: 1033,
    height: 1400,
    title: "Mallard No. 1, Brick Works",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/218-mallard-no-2.avif",
    width: 1050,
    height: 1400,
    title: "Mallard No. 2",
    year: "",
    medium: '14" x 10.25"',
    watercolours: true,
  },
  {
    src: "images/219-rockhopper-penguin.avif",
    width: 967,
    height: 1400,
    title: "Rockhopper Penguin",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/220-still-life-with-sunflowers.avif",
    width: 853,
    height: 1400,
    title: "Still Life with Sunflowers",
    year: "",
    medium: '15" x 9"',
    watercolours: true,
  },
  {
    src: "images/221-a-monk-s-life.avif",
    width: 507,
    height: 717,
    title: "A Monk's Life",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/222-a-monk-s-life.avif",
    width: 1050,
    height: 1400,
    title: "A Monk's Life",
    year: "2023",
    medium: '20" x 14"',
    notes: "Juried entry to Toronto Watercolour Society Aquavision Group Show - Spring, 2023 - Juror: Ray McNeice",
    watercolours: true,
  },
  {
    src: "images/223-cordoba-cathedral.avif",
    width: 1014,
    height: 1400,
    title: "Cordoba Cathedral",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/224-my-electric-toothbrush.avif",
    width: 1087,
    height: 1400,
    title: "My Electric Toothbrush",
    year: "",
    medium: '12" x 8"',
    watercolours: true,
  },
  {
    src: "images/225-brick-works-on-ice.avif",
    width: 1050,
    height: 1400,
    title: "Brick Works on Ice",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/226-at-the-brick-works.avif",
    width: 1050,
    height: 1400,
    title: "At the Brick Works",
    year: "",
    medium: '24" x 18"',
    watercolours: true,
  },
  {
    src: "images/227-life-preserver-brick-works.avif",
    width: 1400,
    height: 1050,
    title: "Life Preserver, Brick Works",
    year: "",
    medium: '18" x 24"',
    watercolours: true,
  },
  {
    src: "images/228-stump-decay-lake-simcoe.avif",
    width: 1050,
    height: 1400,
    title: "Stump Decay, Lake Simcoe",
    year: "",
    medium: '14" x 10"',
    watercolours: true,
  },
  {
    src: "images/229-meadow-in-winter-no-2-de-grassi-point.avif",
    width: 1050,
    height: 1400,
    title: "Meadow in Winter No. 2, De Grassi Point",
    year: "",
    medium: '30" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/230-sunlit-shore-in-winter.avif",
    width: 1009,
    height: 632,
    title: "Sunlit Shore in Winter",
    year: "2023-12-31",
    medium: '15" x 22"',
    watercolours: true,
  },
  {
    src: "images/231-floating-heart-bay-lake-superior.avif",
    width: 1400,
    height: 1050,
    title: "Floating Heart Bay, Lake Superior",
    year: "",
    medium: '15" x 22.5"',
    watercolours: true,
  },
  {
    src: "images/232-st-george-s-grenada.avif",
    width: 1027,
    height: 777,
    title: "St. George's, Grenada",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/233-annandale-falls-grenada.avif",
    width: 1400,
    height: 1050,
    title: "Annandale Falls, Grenada",
    year: "",
    medium: '12" x 16"',
    watercolours: true,
  },
  {
    src: "images/234-beach-umbrellas-galore.avif",
    width: 1258,
    height: 441,
    title: "Beach Umbrellas galore",
    year: "2017",
    medium: '9" x 28"',
    watercolours: true,
  },
  {
    src: "images/235-ski-spray.avif",
    width: 1400,
    height: 557,
    title: "Ski Spray",
    year: "2025-10",
    medium: '11" x 20"',
    watercolours: true,
  },
  {
    src: "images/236-good-vibrations.avif",
    width: 955,
    height: 344,
    title: "Good Vibrations",
    year: "2024-08-14",
    medium: '11" x 30"',
    watercolours: true,
  },
];
